Traceback (most recent call last):
  File "/Users/yilonghao/Library/Python/3.9/lib/python/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/yilonghao/Library/Python/3.9/lib/python/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/yilonghao/Library/Python/3.9/lib/python/site-packages/jupyter_core/utils/__init__.py", line 173, in wrapped
    return loop.run_until_complete(inner)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/yilonghao/Library/Python/3.9/lib/python/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/Users/yilonghao/Library/Python/3.9/lib/python/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/yilonghao/Library/Python/3.9/lib/python/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
LogisticRegression(penalty='l2', dual=False, tol=0.0001, C=1.0, fit_intercept=True, intercept_scaling=1, class_weight=None, random_state=None, solver='liblinear', max_iter=100, multi_class='ovr', verbose=0, warm_start=False, n_jobs=1)
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[3], line 1[0m
[0;32m----> 1[0m [43mLogisticRegression[49m(penalty[38;5;241m=[39m[38;5;124m'[39m[38;5;124ml2[39m[38;5;124m'[39m, dual[38;5;241m=[39m[38;5;28;01mFalse[39;00m, tol[38;5;241m=[39m[38;5;241m0.0001[39m, C[38;5;241m=[39m[38;5;241m1.0[39m, fit_intercept[38;5;241m=[39m[38;5;28;01mTrue[39;00m, intercept_scaling[38;5;241m=[39m[38;5;241m1[39m, class_weight[38;5;241m=[39m[38;5;28;01mNone[39;00m, random_state[38;5;241m=[39m[38;5;28;01mNone[39;00m, solver[38;5;241m=[39m[38;5;124m'[39m[38;5;124mliblinear[39m[38;5;124m'[39m, max_iter[38;5;241m=[39m[38;5;241m100[39m, multi_class[38;5;241m=[39m[38;5;124m'[39m[38;5;124movr[39m[38;5;124m'[39m, verbose[38;5;241m=[39m[38;5;241m0[39m, warm_start[38;5;241m=[39m[38;5;28;01mFalse[39;00m, n_jobs[38;5;241m=[39m[38;5;241m1[39m)

[0;31mNameError[0m: name 'LogisticRegression' is not defined

